"""
Name: Jalen Vaughn
Date: 2/20/24
File: main.py
Description: This module contains the solution for Question 1 on Assignment 6.
Dependencies/Imports: None
"""


class Utils:
    """
    This class contains utility/helper functions.
    """
    
    @staticmethod
    def print_error(msg) -> None:
        """
        Prints an error message
        :param msg: Error message to print
        """
        
        Utils.print_header("Program Error")
        print(msg)
    
    @staticmethod
    def get_user_int() -> int:
        """
        Gets an input from the user and returns the value if it is a validated integer.
        :return: Extracted value from the user.
        :rtype: int
        """
        
        while True:
            user_input: str = input("Enter an integer: ")
            
            try:
                output: int = int(user_input)
            except ValueError:
                print(f"Invalid input: '{user_input}'. Your input is not a valid integer.")
                continue
            
            # valid float
            return output
    
    @staticmethod
    def print_header(header=None) -> None:
        """
        Prints a header to the console with a given text inside
        :param header: Optional string to use for the text inside the header.
        """
        
        if header is None:
            print("=" * 50)
            return
        
        # calculate the correct amount of "=" and dead space to properly fit header in the center
        width: int = 50  # total size
        padding: int = (width - len(header)) // 2  # the amount of "=" signs to put on both sides
        print("=" * padding, header, "=" * padding)


class Statistics:
    """
    This class calculates statistical characteristics of a list of integers generated by a range.
    """
    
    def __init__(self):
        # display welcome message
        Utils.print_header("Statistics")
        print("This program calculates the mean, median, and range\n"
              "of a series of numbers generated from:\n"
              "- A start point\n"
              "- An end point (inclusive)\n"
              "- The step size between the points\n\n"
              "Note: The length of the series must be at least 3!")
        
        # call func to set params from user input
        lower_bound, upper_bound, step_size = self.user_input_params()
        
        # create attribute using comprehension and range
        self.__values: list[int] = [x for x in range(lower_bound, upper_bound + 1, abs(step_size))]
        
        # sort list by descending if step size is negative
        if step_size < 0:
            self.__values = sorted(self.__values, reverse=True)
    
    def user_input_params(self) -> tuple[int, int, int]:
        """
        Obtains statistical parameters (lower bound, upper bound, step size) from user input, checks for errors, and
        returns the values as a tuple
        :return: (lower_bound, upper_bound, step_size)
        :rtype: tuple[int, int, int]
        """
        
        while True:
            # obtain lower boundary from user
            Utils.print_header("Lower Boundary")
            lower_bound: int = Utils.get_user_int()
            
            # obtain upper boundary
            Utils.print_header("Upper Boundary")
            upper_bound: int = Utils.get_user_int()
            
            # Logic error: Lower boundary cannot be greater than Upper
            if lower_bound >= upper_bound:
                Utils.print_error(
                    f"Invalid input: Upper Bound\nUpper bound must be greater than lower bound: {lower_bound}")
                continue
            
            # Call error if boundaries are adjacent
            if lower_bound in [upper_bound - 1, upper_bound + 1]:
                Utils.print_error(f"Warning: The boundaries {lower_bound, upper_bound} are too close to\n"
                                  "generate a valid series of numbers (minimum length of 3).")
                continue
            
            # obtain step size
            Utils.print_header("Step Size")
            print(f"A positive step size will count up from {lower_bound} to {upper_bound}")
            print(f"A negative step size will count down from {upper_bound} to {lower_bound}")
            Utils.print_header()
            step_size: int = Utils.get_user_int()
            
            # Logic error: Impossible to step by zero
            if step_size == 0:
                Utils.print_error(f"Invalid input: Step Size\nStep size cannot be zero.")
                continue
            
            # Series Validation error: Length of list must be at least 3
            if lower_bound + abs(step_size * 2) > upper_bound:
                Utils.print_error("Warning: The combination of boundaries and step size\n"
                                  "leads to a series that is too small.")
                continue
            
            return lower_bound, upper_bound, step_size
    
    def mean(self) -> float:
        """
        Calculates the mean of the list values
        :return: Mean of the list values
        :rtype: float
        """
        
        return sum(self.__values) / len(self.__values)
    
    def median(self) -> float:
        """
        Calculates the median of the list values
        :return: Median of the list values
        :rtype: float
        """
        
        # get specific formula based on list length
        if len(self.__values) % 2 == 0:
            # Even: return mean of two center values
            return (self.__values[len(self.__values) // 2] + self.__values[(len(self.__values) // 2) - 1]) / 2
        else:
            # Odd: return center value
            return float(self.__values[(len(self.__values) // 2)])
    
    def range(self) -> int:
        """
        Calculates the range of the list values
        :return: Range of the list values
        :rtype: int
        """
        
        return max(self.__values) - min(self.__values)
    
    def display_stats(self) -> None:
        """
        Displays all the statistical characteristics of the value list
        """
        
        Utils.print_header("Statistic Info")
        return print(f"Values: {self.__values}\n"
                     f"Mean: {self.mean():.2f}\n"
                     f"Median: {self.median():.2f}\n"
                     f"Range: {self.range()}")


def run_script() -> None:
    """
    Main function of the program meant to fulfill the script purpose:
    1. Creates a Statistics object.
    2. Gets the lower, upper, and step size from the user
    3. Validates the user input and check for logical errors.
    4. Prints the statistics to the console.
    """
    
    # Create Statistic object and display results
    stats: Statistics = Statistics()
    stats.display_stats()


run_script()
